const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Camera3D,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{posX: 0},
	{posY: 0},
	{isPassive: 0},
	{DragDrop: 0},
	{Tween: 0},
	{Flash: 0},
	{upArrow: 0},
	{downArrow: 0},
	{ruleA: 0},
	{ruleH: 0},
	{ruleP: 0},
	{electronCount: 0},
	{upArrowFill: 0},
	{downArrowFill: 0},
	{downArrowUID: 0},
	{upArrowUID: 0},
	{isActive: 0},
	{orbitalType: 0},
	{energyLevel: 0},
	{"1s": 0},
	{"2s": 0},
	{"2p": 0},
	{"3s": 0},
	{"3p": 0},
	{"4s": 0},
	{"3d": 0},
	{metinkutusu: 0},
	{kutuborder: 0},
	{energy: 0},
	{arkaplan: 0},
	{upArrowBg: 0},
	{dizilim: 0},
	{Browser: 0},
	{downArrowBg: 0},
	{ruleA2: 0},
	{ruleH2: 0},
	{ruleP2: 0},
	{fullScreenBtn: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{Touch: 0},
	{Audio: 0},
	{Mouse: 0},
	{"3DCamera": 0},
	{orbitals: 0},
	{buttons: 0},
	{orbitalCount: 0},
	{target3dOrbitalX: 0},
	{target3dOrbitalY: 0},
	{HundControl: 0},
	{activeHundTypeIsUp: 0},
	{soundControl: 0},
	{arrowUID: 0},
	{pointX: 0},
	{pointY: 0},
	{multiType: 0},
	{hundType: 0},
	{setHundTypeReady: 0},
	{isUp: 0},
	{isUpArrow: 0}
];

self.InstanceType = {
	upArrow: class extends self.ISpriteInstance {},
	downArrow: class extends self.ISpriteInstance {},
	ruleA: class extends self.ISpriteInstance {},
	ruleH: class extends self.ISpriteInstance {},
	ruleP: class extends self.ISpriteInstance {},
	_1s: class extends self.ISpriteInstance {},
	_2s: class extends self.ISpriteInstance {},
	_2p: class extends self.ISpriteInstance {},
	_3s: class extends self.ISpriteInstance {},
	_3p: class extends self.ISpriteInstance {},
	_4s: class extends self.ISpriteInstance {},
	_3d: class extends self.ISpriteInstance {},
	metinkutusu: class extends self.ISpriteInstance {},
	kutuborder: class extends self.ISpriteInstance {},
	energy: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	upArrowBg: class extends self.ISpriteInstance {},
	dizilim: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	downArrowBg: class extends self.ISpriteInstance {},
	ruleA2: class extends self.ISpriteInstance {},
	ruleH2: class extends self.ISpriteInstance {},
	ruleP2: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	_3DCamera: class extends self.IInstance {},
	orbitals: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {}
}